profile_sheet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ps_core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

ps_core/urls.py
from django.urls import path, include

from ps_core.views import SkillMasterIndexView, SkillMasterDetailView, UpdateRequestCreateView, UpdateRequestDetailView, \
    SkillMasterSummary, SkillMasterChartData

app_name = "ps_core"
urlpatterns = [
    path(
        '',
        SkillMasterIndexView.as_view(),
        name="index"
    ),
    path(
        'skill_master/detail/<int:pk>',
        SkillMasterDetailView.as_view(),
        name="skill_master_detail"
    ),
    path(
        'update_request/<int:pk>',
        UpdateRequestDetailView.as_view(),
        name="update_request_detail"
    ),
    path(
        'update_request/create/',
        UpdateRequestCreateView.as_view(),
        name="update_request_create"
    ),
    path(
        'skill_master/summary/',
        SkillMasterSummary.as_view(),
        name="skill_master_summary"
    ),
    path(
        'skill_master/chart/api2/',
        SkillMasterChartData.as_view(),
        name='api-data-2',
    ),
]

ps_core/models.py
from django.db import models

# Create your models here.
from django.utils.timezone import now


class Skill(models.Model):
    name = models.CharField(
        max_length=20,
        unique=True,
    )
    description = models.CharField(
        max_length=200,
    )
    skill_group = models.ForeignKey(
        "SkillGroup",
        on_delete=models.CASCADE,
        null=True,
    )

    def __str__(self):
        return self.name


class Rank(models.Model):
    name = models.CharField(
        max_length=20,
        unique=True,
    )
    description = models.CharField(
        max_length=200,
    )

    def __str__(self):
        return self.name


class ReferenceRank(models.Model):
    yoe = models.IntegerField(default=0)
    skill = models.ForeignKey(
        Skill,
        on_delete=models.CASCADE,
    )
    rank = models.ForeignKey(
        Rank,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return ",".join([self.skill.name, self.rank.name, str(self.yoe)])

    class Meta:
        unique_together = ('yoe', 'skill')


class SkillGroup(models.Model):
    name = models.CharField(max_length=100)
    upper_skill_group = models.ForeignKey(
        "SkillGroup",
        on_delete=models.CASCADE,
        null=True,
        blank=True,
        related_name="lower_skill_group_set",
    )

    def __str__(self):
        return self.name


from users.models import User


class SkillMaster(models.Model):
    skill = models.ForeignKey(
        Skill,
        on_delete=models.CASCADE,
    )
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    rank = models.ForeignKey(
        Rank,
        on_delete=models.CASCADE,
    )

    def __str__(self):
        return ", ".join([self.user.username, self.skill.name, self.rank.name])

    class Meta:
        unique_together = ('skill', 'user')


class Status(models.Model):
    name = models.CharField(max_length=255)
    description = models.CharField(max_length=1023)

    def __str__(self):
        return self.name


class UpdateRequest(models.Model):
    skill_master = models.ForeignKey(
        SkillMaster,
        on_delete=models.CASCADE,
    )
    rank_cur = models.ForeignKey(
        Rank,
        on_delete=models.CASCADE,
        related_name='current_rank',
        null=True,
        verbose_name="current rank"
    )
    rank_req = models.ForeignKey(
        Rank,
        on_delete=models.CASCADE,
        related_name='request_rank',
        null=True,
        verbose_name="request rank"
    )
    status = models.ForeignKey(
        Status,
        on_delete=models.CASCADE,
    )
    approver = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
    )
    reason = models.CharField(
        max_length=1023,
        null=False,
        blank=False,
    )
    comment = models.CharField(
        max_length=1023,
        null=True,
        blank=True,
    )

    date_req = models.DateTimeField(
        verbose_name="request date",
        default=now,
    )

    date_app = models.DateTimeField(
        verbose_name="approved date",
        default=now,
    )

    # def __str__(self):
    #     return self.skill_master.user.username + " requests " + \
    #            self.skill_master.skill.name + " rank from " + \
    #            self.rank_cur.name + " to " + self.rank_req.name

    class Meta:
        permissions = (
            ("can_create", "Can create update request"),
            ("can_approve", "Can approve update request")
        )

ps_core/forms.py
from django import forms
from django.forms import models

from ps_core.models import UpdateRequest


class UpdateRequestCreateForm(models.ModelForm):

    class Meta:
        model = UpdateRequest
        fields = ('rank_req', 'reason',)
        widgets = {
            'reason': forms.Textarea(attrs={'style':'width: 100%; height: 5em;'})
        }


class UpdateRequestApproveForm(models.ModelForm):

    class Meta:
        model = UpdateRequest
        fields = ('status', 'comment',)
        widgets = {
            'comment': forms.Textarea(attrs={'style':'width: 100%; height: 5em;'})
        }

ps_core/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin, PermissionRequiredMixin
from django.http import JsonResponse
from django.shortcuts import render

from rest_framework.views import APIView
from rest_framework.response import Response

# Create your views here.
from django.urls import reverse, reverse_lazy
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, UpdateView, TemplateView
from django.views.generic.edit import ModelFormMixin

from ps_core.forms import UpdateRequestCreateForm, UpdateRequestApproveForm
from ps_core.models import SkillMaster, UpdateRequest, Status, Rank, SkillGroup, ReferenceRank, Skill
from users.models import User, Unit


class SkillMasterIndexView(PermissionRequiredMixin, ListView):
    model = SkillMaster
    template_name = 'ps_core/skill_master_index.html'
    permission_required = (
        'ps_core.can_create',
    )
    raise_exception = False
    login_url = reverse_lazy('login')

    def get_queryset(self):
        return SkillMaster.objects.filter(user=self.request.user)

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data()
        context['yoe'] = self.request.user.get_yoe()
        context['update_request_list'] = \
            UpdateRequest.objects.filter(
                approver=self.request.user
            ).filter(status__name="Waiting").order_by('date_req')
        return context


class SkillMasterDetailView(UserPassesTestMixin, ModelFormMixin, DetailView):
    model = SkillMaster
    template_name = 'ps_core/skill_master_detail.html'
    form_class = UpdateRequestCreateForm

    def get(self, request, *args, **kwargs):
        self.request.session['skill_master_id'] = SkillMaster.objects.get(pk=self.kwargs['pk']).id
        self.request.session['rank_cur_id'] = SkillMaster.objects.get(pk=self.kwargs['pk']).rank.id
        self.request.session['status_id'] = Status.objects.get(name="Waiting").id
        self.request.session['approver_id'] = User.objects.get(username="admin").id
        return super().get(request)

    def test_func(self):
        user = self.request.user
        skill_master_user = SkillMaster.objects.get(pk=self.kwargs['pk']).user
        return user == skill_master_user or user.is_superuser

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['update_request_list'] = \
            UpdateRequest.objects.filter(
                skill_master=SkillMaster.objects.get(pk=self.kwargs['pk'])).order_by('-date_req')
        return context


class UpdateRequestCreateView(CreateView):
    model = UpdateRequest
    form_class = UpdateRequestCreateForm
    success_url = '/'

    def post(self, request, *args, **kwargs):
        form = self.get_form()
        form.instance.skill_master = SkillMaster.objects.get(id=self.request.session['skill_master_id'])
        form.instance.rank_cur = Rank.objects.get(id=self.request.session['rank_cur_id'])
        form.instance.status = Status.objects.get(id=self.request.session['status_id'])
        form.instance.approver = User.objects.get(id=self.request.session['approver_id'])
        del self.request.session['skill_master_id']
        del self.request.session['rank_cur_id']
        del self.request.session['status_id']
        del self.request.session['approver_id']
        if form.is_valid():
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class UpdateRequestDetailView(UpdateView):
    model = UpdateRequest
    template_name = "ps_core/update_request_detail.html"
    form_class = UpdateRequestApproveForm
    success_url = '/'

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        context['update_request'] = update_request = UpdateRequest.objects.get(id=self.kwargs['pk'])
        context['skill_master'] = skill_master = SkillMaster.objects.get(id=update_request.skill_master.id)
        context['update_request_list'] = UpdateRequest.objects.filter(skill_master__user=skill_master.user).filter(skill_master__skill=update_request.skill_master.skill).order_by('-date_app')
        return context

    def get(self, request, *args, **kwargs):
        self.request.session['update_request_id'] = self.kwargs['pk']
        return super().get(request)

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        # ↑とても重要！あとでまとめる。
        form = self.get_form()
        ur_id = self.object.id
        ur_object = UpdateRequest.objects.get(id=ur_id)
        form.instance.approver = ur_object.approver
        form.instance.skill_master = ur_object.skill_master
        form.instance.reason = ur_object.reason
        form.instance.rank_req = ur_object.rank_req
        form.instance.rank_cur = ur_object.rank_cur
        form.instance.date_req = ur_object.date_req
        form.instance.date_app = timezone.now()
        del self.request.session['update_request_id']
        if form.is_valid():
            if form.instance.status == Status.objects.get(name="Approved"):
                sm = SkillMaster.objects.get(id=ur_object.skill_master.id)
                sm.rank = ur_object.rank_req
                sm.save()
            return self.form_valid(form)
        else:
            return self.form_invalid(form)


class SkillMasterSummary(UserPassesTestMixin, TemplateView):
    template_name = "ps_core/skill_master_summary.html"

    def test_func(self):
        user = self.request.user
        if user.is_anonymous:
            return False
        unit_set = user.unit_set.all()
        for u in unit_set:
            if u.manager == user:
                return True
        return False

    def get_context_data(self, **kwargs):
        context = super().get_context_data()
        user = self.request.user
        unit = user.unit_set.first()
        member = unit.get_member()
        context['member'] = member.exclude(id=user.id)
        return context


class SkillMasterChartData(APIView):
    authentication_classes = []
    permission_classes = []

    def get(self, request, format=None):
        user = User.objects.get(id=1)
        unit_set = Unit.objects.filter(manager=user)

        # 自分がmanagerを勤めているunitのリストでしかない。
        # 半分abstractみたいなもので、ここにはメンバーはいない。
        data = {
            "id": 0,
            "subs": self.extract_subs(unit_set),
            "member": [],
        }
        return Response(data)

    def extract_subs(self, unit_set):
        result = []
        if unit_set.first() is None:
            return result
        else:
            for unit in unit_set:
                unit_data = {
                    "id": unit.id,
                    "subs": [],
                    "member": [],
                }
                if unit.has_lower_unit():
                    unit_data["subs"] = self.extract_subs(unit.get_lower_unit_set())
                if unit.has_member():
                    unit_data["member"] = self.extract_member(unit)
                result.append(unit_data)
            return result

    def extract_member(self, unit):
        result = []
        member = unit.get_member()
        for user in member:
            user_data = {
                "id": user.id,
                "name": user.username,
                "yoe": user.get_yoe(),
                "skill_group": self.extract_skill_group(user=user),
            }
            result.append(user_data)
        return result

    def extract_skill_group(self, user: User, skill_group: SkillGroup=None):
        result = []
        if skill_group is None:
            skill_group_follow = user.skill_group_follow.all()
        else:
            skill_group_follow = skill_group.lower_skill_group_set.all()
        for sg in skill_group_follow:
            sg_data = {
                "id": sg.id,
                "name": sg.name,
                "skill_group": self.extract_skill_group(user=user, skill_group=sg),
                "skill": self.extract_skill(user=user, skill_group=sg)
            }
            result.append(sg_data)
        return result

    def extract_skill(self, user: User, skill_group: SkillGroup):
        skill_set = skill_group.skill_set.all()
        if skill_set.first() is None:
            return []
        skill_data = {
            "label": [],
            "user_data": [],
            "ref_data": [],
        }
        for skill in skill_set:
            skill_data["label"].append(skill.name)
            skill_data["user_data"].append(self.extract_rank(user, skill))
            skill_data["ref_data"].append(self.extract_ref_rank(user, skill))
        return skill_data

    def extract_rank(self, user: User, skill: Skill):
        skill_master = SkillMaster.objects.filter(user=user).filter(skill=skill).first()
        if skill_master is not None:
            return self.conv_rank(skill_master.rank.name)

    def extract_ref_rank(self, user: User, skill: Skill):
        ref_rank = ReferenceRank.objects.filter(yoe=user.get_yoe()).filter(skill=skill).first()
        if ref_rank is not None:
            return self.conv_rank(ref_rank.rank.name)

    def conv_rank(self, rank: str):
        if rank is "A":
            return 5
        elif rank is "B":
            return 4
        elif rank is "C":
            return 3
        elif rank is "D":
            return 2
        elif rank is "E":
            return 1
        else:
            return 0

ps_core/templates/ps_core/skill_master_detail.html
{% extends "base.html" %}

{% load ps_extras %}

{% block title %}Detail{% endblock title %}

{% block content %}

<form method="post" action="{% url "ps_core:update_request_create" %}">
{% csrf_token %}
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 p-3">
            <div class="row px-3">
                <div class="col-6 p-1">
                    <div class="col-12">
                    スキル：<p class="text-center bg-light rounded" style="font-size: 1.5rem">{{ skillmaster.skill.name }}</p>
                    </div>
                </div>

                <div class="col-6 px-1">
                    <div class="col-12">
                    説明：<p class="p-1 bg-light rounded" style="text-indent:1em;">{{ skillmaster.skill.description }}</p>
                    </div>
                </div>

                <div class="col-6 p-1">
                    <div class="col-12">
                    現在レベル：<p class="text-center bg-light rounded" style="font-size: 1.5rem">{{ skillmaster.rank.name }}</p>
                    </div>
                </div>

                <div class="col-6 px-1">
                    <div class="col-12">
                    申請レベル：<p class="text-center bg-light rounded" style="font-size: 1.5rem">{{ form.rank_req }}</p>
                    </div>
                </div>

                <div class="col-12 px-1">
                    <div class="col-12">
                    理由：<div class="bg-light rounded">{{ form.reason }}</div>
                    </div>
                </div>

                <div class="col-12 py-4 px-0">
                    <div class="col-12">
                    <button type="submit" class="btn btn-primary btn-block" value="submit">レベルアップ申請</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</form>

{% if update_request_list %}
<hr>
<h4>過去の申請</h4>
{% endif %}
{% for ur in update_request_list %}
    <div class="card mb-5">
        <table class="table mb-0 bg-light">
            <tr>
                <td width="15%"><strong>申請内容</strong></td>
                <td colspan="3">{{ ur.rank_cur }}：{{ ur.rank_cur.description }} → {{ ur.rank_req }}：{{ ur.rank_req.description }}</td>
            </tr>
            <tr>
                <td width="15%"><strong>申請理由</strong></td>
                <td colspan="3">{{ ur.reason }}</td>
            </tr>
            <tr>
                <td width="15%"><strong>承認コメント</strong></td>
                <td colspan="3">{{ ur.comment }}</td>
            </tr>
            <tr>
                <td width="15%"><strong>承認状況</strong></td>
                <td width="50%">{{ ur.status }}（{{ ur.date_app }}）</td>
                <td width="15%"><strong>承認者</strong></td>
                <td width="20%">{{ ur.approver.username }}</td>
            </tr>
        </table>
    </div>
{% endfor %}

{% endblock content %}

ps_core/templates/ps_core/skill_master_index.html
{% extends "base.html" %}

{% load ps_extras %}

{% block title %}Home{% endblock title %}

{% block content %}

{% if perms.ps_core.can_create %}
    {% for sm in skillmaster_list %}
        <div class="row">
            <div class="col-md-10 offset-md-1">
                <div class="card my-2">
                <h5 class="card-header">
                    <div class="card-title mb-0">{{ sm.skill.name }}</div>
                </h5>
                <div class="card-body p-0">
                <table class="table mb-0 text-center">
                    <thead>
                        <tr>
                            <th>あなたのレベル</th>
                            <th>参考レベル</th>
                            <th>最終承認日</th>
                            <th>レベルアップ</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="align-middle"><strong style="font-size: 1.3rem">{{ sm.rank.name }}</strong></td>
                            <td class="align-middle">{{ sm.skill.referencerank_set|ref_rank_filter:yoe }}</td>
                            <td class="align-middle">2019/7/1</td>
                            <td><a href="{% url 'ps_core:skill_master_detail' pk=sm.id %}" class="btn btn-primary">申請</a></td>
                        </tr>
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
    {% endfor %}
{% endif %}


{% if perms.ps_core.can_approve %}
    {% for ur in update_request_list %}
        <div class="row">
            <div class="col-md-10 offset-md-1">
                <div class="card my-2">
                <div class="card-header">
                    <h5 class="card-title mb-0">{{ ur.skill_master.user.username }}さんの申請</h5>
                </div>
                <div class="card-body p-0">
                <table class="table mb-0 text-center">
                    <thead>
                        <tr>
                            <th>申請日</th>
                            <th>スキル</th>
                            <th>現ランク</th>
                            <th></th>
                            <th>申請ランク</th>
                            <th>ステータス</th>
                            <th>承認</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td class="align-middle">{{ ur.date_req }}</td>
                            <td class="align-middle">{{ ur.skill_master.skill.name }}</td>
                            <td class="align-middle">{{ ur.rank_cur }}</td>
                            <td class="align-middle">→</td>
                            <td class="align-middle"><strong style="font-size: 1.3rem">{{ ur.rank_req }}</strong></td>
                            <td class="align-middle">{{ ur.status }}</td>
                            <td class="align-middle"><a href="{% url 'ps_core:update_request_detail' pk=ur.id %}" class="btn btn-primary">着手</a></td>
                        </tr>
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
    {% endfor %}
{% endif %}

{% endblock content %}

ps_core/templates/ps_core/skill_master_summary.html
{% extends "base.html" %}

{% load ps_extras %}

{% block title %}Summary{% endblock title %}

<script>
{% block jquery %}

$.ajax({
    method: "GET",
    url: '/skill_master/chart/api2/',
    success: function(data2){
        console.log(data2);
        subDivTest2(data2)
    },
    error: function(error_data){
        console.log("error");
        console.log(error_data);
    }
});

function subDivTest2(subs) {
    $("#canvases").append("<div class='col-sm-12' id='" + subId(subs.id) + "'></div>");
    subDivRec(subs.subs, subs.id);
}

function subDivRec(subs, prevId) {
    for(let i = 0; i < subs.length; i++) {
        $(subId(prevId, "#")).append("<div class='col-sm-12'><div class='row' id='" + subId(subs[i].id) + "'></div></div>");
        subDivRec(subs[i].subs, subs[i].id);
        for(let j = 0; j < subs[i].member.length; j++) {
            $(subId(subs[i].id, "#")).append("<div class='col-lg-4 col-sm-6 col-xs-12'><div class='card m-1 p-0' id='" + memberId(subs[i].member[j].id) + "'></div></div>");
            $(memberId(subs[i].member[j].id, "#")).append("<div class='card-header'><h5 class='card-title mb-0'>" + subs[i].member[j].name + "（" + subs[i].member[j].yoe +"年次）" + "</h5></div>");
            skillGroupRec(subs[i].member[j].skill_group, memberId(subs[i].member[j].id), subs[i].member[j].id);
        }
    }
}

function skillGroupRec(skill_group_set, id, memberNo) {
    for(let i = 0; i < skill_group_set.length; i++) {
        $("#" + id).append("<div class='col-sm-12' id='" + skillGroupId(memberNo, skill_group_set[i].id) + "'></div>");
        $(skillGroupId(memberNo, skill_group_set[i].id, "#")).append("<h6>" + skill_group_set[i].name + "</h6>");
        skillGroupRec(skill_group_set[i].skill_group, skillGroupId(memberNo, skill_group_set[i].id), memberNo);
        skillChart(skill_group_set[i].skill, skillGroupId(memberNo, skill_group_set[i].id));
    }
}

function skillChart(skill_set, id) {
    if(skill_set.length != 0) {
        $("#" + id).append("<canvas width='400' height='400'  id='" + canvasId(id) + "'></canvas>");
        drawChart(canvasId(id), skill_set.label, skill_set.user_data, skill_set.ref_data);
    }
}

function subId(id=0, selector="") {
    return (selector + "sub_" + id);
}

function memberId(id=0, selector="") {
    return (selector + "member_" + id);
}

function skillGroupId(member_id=0, skill_group_id=0, selector="") {
    return (selector + "member_" + member_id + "_skill_group_" + skill_group_id);
}

{# skillGroupId を受け取るという点で他と異なる #}
function canvasId(skill_group_id=0, selector="") {
    return (selector + skill_group_id + "_canvas")
}

let userBorderColor = [
    'rgba(54, 162, 235, 1)',
];

let userBackgroundColor = [
    'rgba(54, 162, 235, 0.2)',
];

let refBorderColor = [
    'rgba(255, 99, 132, 1)'
];

let refBackgroundColor = [
    'rgba(255, 99, 132, 0.2)'
];

function drawChart(canvasId, labels, user_data, ref_data) {
    var ctx = document.getElementById(canvasId).getContext('2d');
    var myChart = new Chart(ctx, {
        type: 'radar',
        data: {
            labels: labels,
            datasets: [{
                label: "本人レベル",
                data: user_data,
                backgroundColor: userBackgroundColor,
                borderColor: userBorderColor,
                borderWidth: 2
            }, {
                label: "年次目安",
                data: ref_data,
                backgroundColor: refBackgroundColor,
                borderColor: refBorderColor,
                borderWidth: 1
            }]
        },
        options: {
            scale: {
                ticks: {
                    beginAtZero: true,
                    min: 0,
                    max: 5,
                    stepSize: 1
                }
            }
        }
    });
}

{% endblock %}
</script>

{% block content %}

    <h4 id="title_call">Skill Master Summary</h4>
    <div class="row" id="canvases"></div>

{% endblock content %}

ps_core/templates/ps_core/update_request_detail.html
{% extends "base.html" %}

{% load ps_extras %}

{% block title %}Approve{% endblock title %}

{% block content %}


<form method="post" action="{% url "ps_core:update_request_detail" pk=object.id %}">
{% csrf_token %}
<div class="container-fluid">
    <div class="row">
        <div class="col-xs-12 p-3">
            <div class="row px-3">
                <div class="col-6 p-1">
                    <div class="col-12">
                    スキル：<p class="text-center bg-light rounded" style="font-size: 1.5rem">{{ skill_master.skill.name }}</p>
                    </div>
                </div>

                <div class="col-6 px-1">
                    <div class="col-12">
                    説明：<p class="p-1 bg-light rounded" style="text-indent:1em;">{{ skill_master.skill.description }}</p>
                    </div>
                </div>

                <div class="col-6 p-1">
                    <div class="col-12">
                    現在レベル：<p class="text-center bg-light rounded" style="font-size: 1.5rem">{{ skill_master.rank.name }}</p>
                    </div>
                </div>

                <div class="col-6 px-1">
                    <div class="col-12">
                    申請レベル：<p class="text-center bg-light rounded" style="font-size: 1.5rem">{{ update_request.rank_req }}</p>
                    </div>
                </div>

                <div class="col-12 px-1 pb-3">
                    <div class="col-12">
                    理由：<div class="bg-light rounded">{{ update_request.reason }}</div>
                    </div>
                </div>

                <div class="col-12 px-1">
                    <div class="col-12">
                    コメント：<div class="bg-light rounded">{{ form.comment }}</div>
                    </div>
                </div>

                <div class="col-6 py-4 px-0">
                    <div class="col-12">
                    <p class="text-center bg-light rounded" style="font-size: 1.5rem">判定：{{ form.status }}</p>
                    </div>
                </div>

                <div class="col-6 py-4 px-0">
                    <div class="col-12">
                    <button type="submit" class="btn btn-primary btn-block" value="submit">確認</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</form>

{% if update_request_list %}
<hr>
<h4>過去の申請</h4>
{% endif %}

{% for ur in update_request_list %}
    <div class="card mb-5">
        <table class="table mb-0 bg-light">
            <tr>
                <td width="15%"><strong>申請内容</strong></td>
                <td colspan="3">{{ ur.rank_cur }}：{{ ur.rank_cur.description }} → {{ ur.rank_req }}：{{ ur.rank_req.description }}</td>
            </tr>
            <tr>
                <td width="15%"><strong>申請理由</strong></td>
                <td colspan="3">{{ ur.reason }}</td>
            </tr>
            <tr>
                <td width="15%"><strong>承認コメント</strong></td>
                <td colspan="3">{{ ur.comment }}</td>
            </tr>
            <tr>
                <td width="15%"><strong>承認状況</strong></td>
                <td width="50%">{{ ur.status }}（{{ ur.date_app }}）</td>
                <td width="15%"><strong>承認者</strong></td>
                <td width="20%">{{ ur.approver.username }}</td>
            </tr>
        </table>
    </div>
{% endfor %}


{% endblock content %}