profile_sheet/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ps_core.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

ps_core/urls.py
from django.urls import path, include

from ps_core.views import SkillMasterIndexView, SkillMasterDetailView, UpdateRequestCreateView, UpdateRequestDetailView, \
    SkillMasterSummary, SkillMasterChartData

app_name = "ps_core"
urlpatterns = [
    path(
        '',
        SkillMasterIndexView.as_view(),
        name="index"
    ),
    path(
        'skill_master/detail/<int:pk>',
        SkillMasterDetailView.as_view(),
        name="skill_master_detail"
    ),
    path(
        'update_request/<int:pk>',
        UpdateRequestDetailView.as_view(),
        name="update_request_detail"
    ),
    path(
        'update_request/create/',
        UpdateRequestCreateView.as_view(),
        name="update_request_create"
    ),
    path(
        'skill_master/summary/',
        SkillMasterSummary.as_view(),
        name="skill_master_summary"
    ),
    path(
        'skill_master/chart/api2/',
        SkillMasterChartData.as_view(),
        name='api-data-2',
    ),
]

templates/base.html
<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <title>{% block title %}{% endblock title %} | Profile Sheet</title>

    </head>
    <body>

    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <a class="navbar-brand" href="/"><strong>Profiling Sheet</strong>{% if user.is_authenticated %} - {{ user.username }}（{{ user.get_yoe }}年次）{% endif %}</a>

            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="nav-link" href="{% url 'ps_core:index' %}">Home</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'ps_core:skill_master_summary' %}">Summary</a></li>
            </ul>

            <ul class="navbar-nav navbar-right">
                <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Logout</a></li>
                <li class="nav-item"><a class="nav-link disabled" href="#">Settings</a></li>
            </ul>
    </nav>

        <div class="container">

            {% block content %}
            {% endblock content %}

        </div>

        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <!-- Chart.js -->
        <script src="https://cdn.jsdelivr.net/npm/chart.js@2.8.0/dist/Chart.min.js"></script>

        <script>
            jQuery(function ($) {
                {% block jquery %}{% endblock %}
            });
        </script>

    </body>
</html>